project_id = "ipcjabzvinmzyujsfige"

[functions.methodology]
verify_jwt = false

[functions.subtype]
verify_jwt = false

[functions.colors]
verify_jwt = false

[functions.client-data]
verify_jwt = false

[functions.trainer-data]
verify_jwt = false